# -*- coding: utf-8 -*-
"""EntregaFinal_Despliegue.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e7ZqeO4Ag0DZC70B0B268ZwAEMLFdJh9

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros
- Aplicamos el modelo para la predicción
"""

#Cargamos librerías principales

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Cargamos el modelo
import pickle
filename = 'modelo-ensamble-reg-loads.pkl'
modelo, variables, min_max_scaler = pickle.load(open(filename, 'rb'))

# #Cargamos los datos futuros
# data = pd.read_csv("Predicciones.csv")
# data.head()

#Interfaz gráfica


#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st

st.title('Predicción de cargas - Complex')

SH6231 = st.slider('UsodeDisp_6231', min_value=0, max_value=1, value=0, step=0.01)
SH6232 = st.slider('UsodeDisp_6232', min_value=0, max_value=1, value=0, step=0.01)
SH6233 = st.slider('UsodeDisp_6233', min_value=0, max_value=1, value=0, step=0.01)
SH6234 = st.slider('UsodeDisp_6234', min_value=0, max_value=1, value=0, step=0.01)
SH6235 = st.slider('UsodeDisp_6235', min_value=0, max_value=1, value=0, step=0.01)
SH6236 = st.slider('UsodeDisp_6236', min_value=0, max_value=1, value=0, step=0.01)
SH6237 = st.slider('UsodeDisp_6237', min_value=0, max_value=1, value=0, step=0.01)
SH6238 = st.slider('UsodeDisp_6238', min_value=0, max_value=1, value=0, step=0.01)
SH6239 = st.slider('UsodeDisp_6239', min_value=0, max_value=1, value=0, step=0.01)
SH6241 = st.slider('UsodeDisp_6241', min_value=0, max_value=1, value=0, step=0.01)
SH6242 = st.slider('UsodeDisp_6242', min_value=0, max_value=1, value=0, step=0.01)
SH6243 = st.slider('UsodeDisp_6243', min_value=0, max_value=1, value=0, step=0.01)
SH6244 = st.slider('UsodeDisp_6244', min_value=0, max_value=1, value=0, step=0.01)
SH6245 = st.slider('UsodeDisp_6245', min_value=0, max_value=1, value=0, step=0.01)
SH6246 = st.slider('UsodeDisp_6246', min_value=0, max_value=1, value=0, step=0.01)
SH6247 = st.slider('UsodeDisp_6247', min_value=0, max_value=1, value=0, step=0.01)
SH6248 = st.slider('UsodeDisp_6248', min_value=0, max_value=1, value=0, step=0.01)
SH6249 = st.slider('UsodeDisp_6249', min_value=0, max_value=1, value=0, step=0.01)
SH6250 = st.slider('UsodeDisp_6250', min_value=0, max_value=1, value=0, step=0.01)
SH6260 = st.slider('UsodeDisp_6260', min_value=0, max_value=1, value=0, step=0.01)
SH6261 = st.slider('UsodeDisp_6261', min_value=0, max_value=1, value=0, step=0.01)
SH6262 = st.slider('UsodeDisp_6262', min_value=0, max_value=1, value=0, step=0.01)
SH6263 = st.slider('UsodeDisp_6263', min_value=0, max_value=1, value=0, step=0.01)
SH6264 = st.slider('UsodeDisp_6264', min_value=0, max_value=1, value=0, step=0.01)
SH6268 = st.slider('UsodeDisp_6268', min_value=0, max_value=1, value=0, step=0.01)
SH6269 = st.slider('UsodeDisp_6269', min_value=0, max_value=1, value=0, step=0.01)
SH6449 = st.slider('UsodeDisp_6449', min_value=0, max_value=1, value=0, step=0.01)
SH6455 = st.slider('UsodeDisp_6455', min_value=0, max_value=1, value=0, step=0.01)
SH6457 = st.slider('UsodeDisp_6457', min_value=0, max_value=1, value=0, step=0.01)
Tks_Availability_OB = st.slider('Tks Availability OB', min_value=0, max_value=1, value=0, step=0.01)
Tks_Utilization_OB = st.slider('Tks Utilised Time', min_value=0, max_value=1, value=0, step=0.01)
Utilization_OB = st.slider('OB Cycle time (Min)', min_value=20, max_value=42, value=0, step=0.1)

SHIFT = st.selectbox('turno', ['D', 'N'])


#Dataframe
datos = [[
    SH6231, SH6232, SH6233, SH6234, SH6235, SH6236, SH6237, SH6238, SH6239,
    SH6241, SH6242, SH6243, SH6244, SH6245, SH6246, SH6247, SH6248, SH6249,
    SH6250, SH6260, SH6261, SH6262, SH6263, SH6264, SH6268, SH6269,
    SH6449, SH6455, SH6457, Tks_Availability_OB, Tks_Utilization_OB,
    Utilization_OB, SHIFT
]]

data = pd.DataFrame(datos, columns=['UsodeDisp_6231','UsodeDisp_6232','UsodeDisp_6233','UsodeDisp_6234','UsodeDisp_6235','UsodeDisp_6236','UsodeDisp_6237','UsodeDisp_6238','UsodeDisp_6239','UsodeDisp_6241','UsodeDisp_6242','UsodeDisp_6243','UsodeDisp_6244','UsodeDisp_6245','UsodeDisp_6246','UsodeDisp_6247','UsodeDisp_6248','UsodeDisp_6249','UsodeDisp_6250','UsodeDisp_6260','UsodeDisp_6261','UsodeDisp_6262','UsodeDisp_6263','UsodeDisp_6264','UsodeDisp_6268','UsodeDisp_6269','UsodeDisp_6449','UsodeDisp_6455','UsodeDisp_6457','Tks Availability OB','Tks Utilised Time','OB Cycle time (Min)']) #Dataframe con los mismos nombres de variables

#Se realiza la preparación de datos
data_preparada=data.copy()

#En despliegue drop_first= False
data_preparada = pd.get_dummies(data_preparada, columns=['turno'], drop_first=False, dtype=int)
data_preparada.head()

#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

#Se normaliza la edad para predecir con Knn, Red, SVM
#En los despliegues no se llama fit
data_preparada[['UsodeDisp_6231','UsodeDisp_6232','UsodeDisp_6233','UsodeDisp_6234','UsodeDisp_6235','UsodeDisp_6236','UsodeDisp_6237','UsodeDisp_6238','UsodeDisp_6239','UsodeDisp_6241','UsodeDisp_6242','UsodeDisp_6243','UsodeDisp_6244','UsodeDisp_6245','UsodeDisp_6246','UsodeDisp_6247','UsodeDisp_6248','UsodeDisp_6249','UsodeDisp_6250','UsodeDisp_6260','UsodeDisp_6261','UsodeDisp_6262','UsodeDisp_6263','UsodeDisp_6264','UsodeDisp_6268','UsodeDisp_6269','UsodeDisp_6449','UsodeDisp_6455','UsodeDisp_6457','Tks Availability OB','Tks Utilised Time','OB Cycle time (Min)']]= min_max_scaler.transform(data_preparada[['UsodeDisp_6231','UsodeDisp_6232','UsodeDisp_6233','UsodeDisp_6234','UsodeDisp_6235','UsodeDisp_6236','UsodeDisp_6237','UsodeDisp_6238','UsodeDisp_6239','UsodeDisp_6241','UsodeDisp_6242','UsodeDisp_6243','UsodeDisp_6244','UsodeDisp_6245','UsodeDisp_6246','UsodeDisp_6247','UsodeDisp_6248','UsodeDisp_6249','UsodeDisp_6250','UsodeDisp_6260','UsodeDisp_6261','UsodeDisp_6262','UsodeDisp_6263','UsodeDisp_6264','UsodeDisp_6268','UsodeDisp_6269','UsodeDisp_6449','UsodeDisp_6455','UsodeDisp_6457','Tks Availability OB','Tks Utilised Time','OB Cycle time (Min)']])
data_preparada.head()

"""##**PREDICCIONES**"""

#Hacemos la predicción con el Tree
Y_pred = modelo.predict(data_preparada)
print(Y_pred)

data['Prediccion']=Y_pred
data.head()

data

# Recordar medida de error del modelo

st.warning("El modelo tiene un error del 1.5%")